[preferred]
# Use swaysettings and gtk for every portal interface...
default=swaysettings;gtk;
# ... except for the ScreenCast and Screenshot
org.freedesktop.impl.portal.ScreenCast=wlr
org.freedesktop.impl.portal.Screenshot=wlr
org.freedesktop.impl.portal.Secret=gnome-keyring;
